### ISSUE TITLE
macOS 13 CoreGraphics Deprecation

### ISSUE THREAD

**Issue by zukzuk2020** [filipnavara/mac-playground#36]
Not sure it's the right place to bring this up. There's this [upcoming deprecation](https://developer.apple.com/documentation/macos-release-notes/macos-13-release-notes) in macOS 13 in CoreGraphics which I couldn't quickly deduct if it's going to impact the project. 

**_To improve security, CGImageCreate enforces parameter correctness on macOS 13 Ventura, iOS 16, iPadOS 16, watchOS 9, and tvOS 16. Passing an incorrect CGImageByteOrderInfo is no longer supported, and will result in images failing to load. (94855401)_**
 
CGImageCreate is being used in mac-playground, but it's not clear if the deprecation would affect anything. Any input guys? @filipnavara

**Comment by filipnavara** [comment]
Thanks for bringing it up. We believe it would not directly affect the project but we will test on macOS Ventura before it gets released.

(Side note: I didn't sync up the public repository with our internal code for a while. There is a bug in `git subtree` that prevented me from doing it efficiently but since no one cared to fix it for years I will have to find another way. We are still updating the project to keep up with new .NET and macOS releases.)

**Comment by filipnavara** [comment]
The source tree is now in sync with our upstream repository. It was tested on macOS Ventura 13.0 and works fine.

**Comment by zukzuk2020** [comment]
This is great! Thanks for the update.
